---
version: "3.9"
networks:
  Roboshop:
    driver: Bridge
services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  redis:
    image: redis
    container_name: redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: mysql:v1
    container_name: mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq    
  shipping:
    image: shipping:v1
    container_name: shipping    
    depends_on:
      - mysql
  payment:
    image: payment:v1
    container_name: payment    
    depends_on:
      - rabbitmq
  ratings:
    image: ratings:v1
    container_name: ratings
  web:
    image: web:v1
    container_name: web
    ports:
     - "80:80"
    depends_on:
      - mongodb
      - redis
      - user
      - cart
      - shipping
      - payment
      - rabbitmq
      - ratings
      
